//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Office365APIEditor.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastRequest {
            get {
                return ((string)(this["LastRequest"]));
            }
            set {
                this["LastRequest"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastWebAppClientID {
            get {
                return ((string)(this["LastWebAppClientID"]));
            }
            set {
                this["LastWebAppClientID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastWebAppClientSecret {
            get {
                return ((string)(this["LastWebAppClientSecret"]));
            }
            set {
                this["LastWebAppClientSecret"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastNativeAppTenantName {
            get {
                return ((string)(this["LastNativeAppTenantName"]));
            }
            set {
                this["LastNativeAppTenantName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastNativeAppClientID {
            get {
                return ((string)(this["LastNativeAppClientID"]));
            }
            set {
                this["LastNativeAppClientID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastNativeAppRedirectURL {
            get {
                return ((string)(this["LastNativeAppRedirectURL"]));
            }
            set {
                this["LastNativeAppRedirectURL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastWebAppRedirectURL {
            get {
                return ((string)(this["LastWebAppRedirectURL"]));
            }
            set {
                this["LastWebAppRedirectURL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string BasicAuthSmtpAddress {
            get {
                return ((string)(this["BasicAuthSmtpAddress"]));
            }
            set {
                this["BasicAuthSmtpAddress"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>offline_access</string>\r\n  <string>openid</string>\r\n  <string>profile</str" +
            "ing>\r\n  <string>email</string>\r\n  <string>https://outlook.office.com/calendars.r" +
            "ead</string>\r\n  <string>https://outlook.office.com/calendars.read.shared</string" +
            ">\r\n  <string>https://outlook.office.com/calendars.readwrite</string>\r\n  <string>" +
            "https://outlook.office.com/calendars.readwrite.shared</string>\r\n  <string>https:" +
            "//outlook.office.com/contacts.read</string>\r\n  <string>https://outlook.office.co" +
            "m/contacts.readwrite</string>\r\n  <string>https://outlook.office.com/mail.read</s" +
            "tring>\r\n  <string>https://outlook.office.com/mail.readwrite</string>\r\n  <string>" +
            "https://outlook.office.com/mail.send</string>\r\n  <string>https://outlook.office." +
            "com/mailboxsettings.read</string>\r\n  <string>https://outlook.office.com/mailboxs" +
            "ettings.readwrite</string>\r\n  <string>https://outlook.office.com/people.read</st" +
            "ring>\r\n  <string>https://outlook.office.com/tasks.read</string>\r\n  <string>https" +
            "://outlook.office.com/tasks.readwrite</string>\r\n  <string>https://outlook.office" +
            ".com/user.read</string>\r\n  <string>https://outlook.office.com/user.readwrite</st" +
            "ring>\r\n  <string>https://outlook.office.com/user.readbasic.all</string>\r\n  <stri" +
            "ng>https://graph.microsoft.com/Calendars.Read</string>\r\n  <string>https://graph." +
            "microsoft.com/Calendars.Read.Shared</string>\r\n  <string>https://graph.microsoft." +
            "com/Calendars.ReadWrite</string>\r\n  <string>https://graph.microsoft.com/Calendar" +
            "s.ReadWrite.Shared</string>\r\n  <string>https://graph.microsoft.com/Contacts.Read" +
            "</string>\r\n  <string>https://graph.microsoft.com/Contacts.Read.Shared</string>\r\n" +
            "  <string>https://graph.microsoft.com/Contacts.ReadWrite</string>\r\n  <string>htt" +
            "ps://graph.microsoft.com/Contacts.ReadWrite.Shared</string>\r\n  <string>https://g" +
            "raph.microsoft.com/Directory.Read.All</string>\r\n  <string>https://graph.microsof" +
            "t.com/Directory.ReadWrite.All</string>\r\n  <string>https://graph.microsoft.com/Di" +
            "rectory.AccessAsUser.All</string>\r\n  <string>https://graph.microsoft.com/Files.R" +
            "ead</string>\r\n  <string>https://graph.microsoft.com/Files.Read.All</string>\r\n  <" +
            "string>https://graph.microsoft.com/Files.ReadWrite</string>\r\n  <string>https://g" +
            "raph.microsoft.com/Files.ReadWrite.All</string>\r\n  <string>https://graph.microso" +
            "ft.com/Group.Read.All</string>\r\n  <string>https://graph.microsoft.com/Group.Read" +
            "Write.All</string>\r\n  <string>https://graph.microsoft.com/Mail.Read</string>\r\n  " +
            "<string>https://graph.microsoft.com/Mail.ReadWrite</string>\r\n  <string>https://g" +
            "raph.microsoft.com/Mail.Read.Shared</string>\r\n  <string>https://graph.microsoft." +
            "com/Mail.ReadWrite.Shared</string>\r\n  <string>https://graph.microsoft.com/Mail.S" +
            "end</string>\r\n  <string>https://graph.microsoft.com/Mail.Send.Shared</string>\r\n " +
            " <string>https://graph.microsoft.com/MailboxSettings.Read</string>\r\n  <string>ht" +
            "tps://graph.microsoft.com/MailboxSettings.ReadWrite</string>\r\n  <string>https://" +
            "graph.microsoft.com/Notes.Create</string>\r\n  <string>https://graph.microsoft.com" +
            "/Notes.Read</string>\r\n  <string>https://graph.microsoft.com/Notes.ReadWrite</str" +
            "ing>\r\n  <string>https://graph.microsoft.com/Notes.Read.All</string>\r\n  <string>h" +
            "ttps://graph.microsoft.com/Notes.ReadWrite.All</string>\r\n  <string>https://graph" +
            ".microsoft.com/People.Read</string>\r\n  <string>https://graph.microsoft.com/Sites" +
            ".Read.All</string>\r\n  <string>https://graph.microsoft.com/Sites.ReadWrite.All</s" +
            "tring>\r\n  <string>https://graph.microsoft.com/User.Export.All</string>\r\n  <strin" +
            "g>https://graph.microsoft.com/User.Read</string>\r\n  <string>https://graph.micros" +
            "oft.com/User.Read.All</string>\r\n  <string>https://graph.microsoft.com/User.ReadB" +
            "asic.All</string>\r\n  <string>https://graph.microsoft.com/User.ReadWrite</string>" +
            "\r\n  <string>https://graph.microsoft.com/User.ReadWrite.All</string>\r\n  <string>h" +
            "ttps://graph.microsoft.com/UserActivity.ReadWrite.CreatedByApp</string>\r\n</Array" +
            "OfString>")]
        public global::System.Collections.Specialized.StringCollection PredefinedScopes {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["PredefinedScopes"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>offline_access</string>\r\n  <string>https://graph.microsoft.com/Calendars.R" +
            "ead</string>\r\n  <string>https://graph.microsoft.com/Calendars.Read.Shared</strin" +
            "g>\r\n  <string>https://graph.microsoft.com/Calendars.ReadWrite</string>\r\n  <strin" +
            "g>https://graph.microsoft.com/Calendars.ReadWrite.Shared</string>\r\n  <string>htt" +
            "ps://graph.microsoft.com/Contacts.Read</string>\r\n  <string>https://graph.microso" +
            "ft.com/Contacts.Read.Shared</string>\r\n  <string>https://graph.microsoft.com/Cont" +
            "acts.ReadWrite</string>\r\n  <string>https://graph.microsoft.com/Contacts.ReadWrit" +
            "e.Shared</string>\r\n  <string>https://graph.microsoft.com/Mail.Read</string>\r\n  <" +
            "string>https://graph.microsoft.com/Mail.ReadWrite</string>\r\n  <string>https://gr" +
            "aph.microsoft.com/Mail.Read.Shared</string>\r\n  <string>https://graph.microsoft.c" +
            "om/Mail.ReadWrite.Shared</string>\r\n  <string>https://graph.microsoft.com/Mail.Se" +
            "nd</string>\r\n  <string>https://graph.microsoft.com/Mail.Send.Shared</string>\r\n  " +
            "<string>https://graph.microsoft.com/MailboxSettings.Read</string>\r\n  <string>htt" +
            "ps://graph.microsoft.com/MailboxSettings.ReadWrite</string>\r\n  <string>https://g" +
            "raph.microsoft.com/People.Read</string>\r\n  <string>https://graph.microsoft.com/U" +
            "ser.Read</string>\r\n  <string>https://graph.microsoft.com/User.ReadWrite</string>" +
            "\r\n  <string>https://graph.microsoft.com/User.ReadBasic.All</string>\r\n</ArrayOfSt" +
            "ring>")]
        public global::System.Collections.Specialized.StringCollection DefaultScopes {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["DefaultScopes"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection CustomDefinedScopes {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["CustomDefinedScopes"]));
            }
            set {
                this["CustomDefinedScopes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastV2WebAppClientID {
            get {
                return ((string)(this["LastV2WebAppClientID"]));
            }
            set {
                this["LastV2WebAppClientID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastV2WebAppRedirectUri {
            get {
                return ((string)(this["LastV2WebAppRedirectUri"]));
            }
            set {
                this["LastV2WebAppRedirectUri"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastV2WebAppScopes {
            get {
                return ((string)(this["LastV2WebAppScopes"]));
            }
            set {
                this["LastV2WebAppScopes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastV2WebAppClientSecret {
            get {
                return ((string)(this["LastV2WebAppClientSecret"]));
            }
            set {
                this["LastV2WebAppClientSecret"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastV2MobileAppClientID {
            get {
                return ((string)(this["LastV2MobileAppClientID"]));
            }
            set {
                this["LastV2MobileAppClientID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastV2MobileAppScopes {
            get {
                return ((string)(this["LastV2MobileAppScopes"]));
            }
            set {
                this["LastV2MobileAppScopes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool NeedUpgrade {
            get {
                return ((bool)(this["NeedUpgrade"]));
            }
            set {
                this["NeedUpgrade"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastMailboxViewerClientID {
            get {
                return ((string)(this["LastMailboxViewerClientID"]));
            }
            set {
                this["LastMailboxViewerClientID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastWebAppAppOnlyTenantName {
            get {
                return ((string)(this["LastWebAppAppOnlyTenantName"]));
            }
            set {
                this["LastWebAppAppOnlyTenantName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastWebAppAppOnlyClientID {
            get {
                return ((string)(this["LastWebAppAppOnlyClientID"]));
            }
            set {
                this["LastWebAppAppOnlyClientID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastWebAppAppOnlyCertPath {
            get {
                return ((string)(this["LastWebAppAppOnlyCertPath"]));
            }
            set {
                this["LastWebAppAppOnlyCertPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastWebAppAppOnlyCertPass {
            get {
                return ((string)(this["LastWebAppAppOnlyCertPass"]));
            }
            set {
                this["LastWebAppAppOnlyCertPass"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LogFolderPath {
            get {
                return ((string)(this["LogFolderPath"]));
            }
            set {
                this["LogFolderPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Static")]
        public string LogFileStyle {
            get {
                return ((string)(this["LogFileStyle"]));
            }
            set {
                this["LogFileStyle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AllowAutoRedirect {
            get {
                return ((bool)(this["AllowAutoRedirect"]));
            }
            set {
                this["AllowAutoRedirect"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastWebAppAppOnlyByKeyTenantName {
            get {
                return ((string)(this["LastWebAppAppOnlyByKeyTenantName"]));
            }
            set {
                this["LastWebAppAppOnlyByKeyTenantName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastWebAppAppOnlyByKeyClientID {
            get {
                return ((string)(this["LastWebAppAppOnlyByKeyClientID"]));
            }
            set {
                this["LastWebAppAppOnlyByKeyClientID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastWebAppAppOnlyByKeyClientSecret {
            get {
                return ((string)(this["LastWebAppAppOnlyByKeyClientSecret"]));
            }
            set {
                this["LastWebAppAppOnlyByKeyClientSecret"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastBuiltInAppScopes {
            get {
                return ((string)(this["LastBuiltInAppScopes"]));
            }
            set {
                this["LastBuiltInAppScopes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("389b1b32-b5d5-43b2-bddc-84ce938d6737")]
        public string BuiltInAppClientId {
            get {
                return ((string)(this["BuiltInAppClientId"]));
            }
            set {
                this["BuiltInAppClientId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("urn:ietf:wg:oauth:2.0:oob")]
        public string BuiltInAppRedirectUri {
            get {
                return ((string)(this["BuiltInAppRedirectUri"]));
            }
            set {
                this["BuiltInAppRedirectUri"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Office365APIEditor")]
        public string CustomUserAgent {
            get {
                return ((string)(this["CustomUserAgent"]));
            }
            set {
                this["CustomUserAgent"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int CustomUserAgentMode {
            get {
                return ((int)(this["CustomUserAgentMode"]));
            }
            set {
                this["CustomUserAgentMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastV2WebAppAppOnlyByPasswordForMicrosoftGraphTenantName {
            get {
                return ((string)(this["LastV2WebAppAppOnlyByPasswordForMicrosoftGraphTenantName"]));
            }
            set {
                this["LastV2WebAppAppOnlyByPasswordForMicrosoftGraphTenantName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastV2WebAppAppOnlyByPasswordForMicrosoftGraphClientID {
            get {
                return ((string)(this["LastV2WebAppAppOnlyByPasswordForMicrosoftGraphClientID"]));
            }
            set {
                this["LastV2WebAppAppOnlyByPasswordForMicrosoftGraphClientID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastV2WebAppAppOnlyByPasswordForMicrosoftGraphClientSecret {
            get {
                return ((string)(this["LastV2WebAppAppOnlyByPasswordForMicrosoftGraphClientSecret"]));
            }
            set {
                this["LastV2WebAppAppOnlyByPasswordForMicrosoftGraphClientSecret"] = value;
            }
        }
    }
}
