//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Office365APIEditor.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.1.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastRequest {
            get {
                return ((string)(this["LastRequest"]));
            }
            set {
                this["LastRequest"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastWebAppClientID {
            get {
                return ((string)(this["LastWebAppClientID"]));
            }
            set {
                this["LastWebAppClientID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastWebAppClientSecret {
            get {
                return ((string)(this["LastWebAppClientSecret"]));
            }
            set {
                this["LastWebAppClientSecret"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastNativeAppTenantName {
            get {
                return ((string)(this["LastNativeAppTenantName"]));
            }
            set {
                this["LastNativeAppTenantName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastNativeAppClientID {
            get {
                return ((string)(this["LastNativeAppClientID"]));
            }
            set {
                this["LastNativeAppClientID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastNativeAppRedirectURL {
            get {
                return ((string)(this["LastNativeAppRedirectURL"]));
            }
            set {
                this["LastNativeAppRedirectURL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastWebAppRedirectURL {
            get {
                return ((string)(this["LastWebAppRedirectURL"]));
            }
            set {
                this["LastWebAppRedirectURL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string BasicAuthSmtpAddress {
            get {
                return ((string)(this["BasicAuthSmtpAddress"]));
            }
            set {
                this["BasicAuthSmtpAddress"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>offline_access</string>\r\n  <string>openid</string>\r\n  <string>profile</str" +
            "ing>\r\n  <string>email</string>\r\n  <string>https://outlook.office.com/calendars.r" +
            "ead</string>\r\n  <string>https://outlook.office.com/calendars.read.shared</string" +
            ">\r\n  <string>https://outlook.office.com/calendars.readwrite</string>\r\n  <string>" +
            "https://outlook.office.com/calendars.readwrite.shared</string>\r\n  <string>https:" +
            "//outlook.office.com/contacts.read</string>\r\n  <string>https://outlook.office.co" +
            "m/contacts.readwrite</string>\r\n  <string>https://outlook.office.com/mail.read</s" +
            "tring>\r\n  <string>https://outlook.office.com/mail.readwrite</string>\r\n  <string>" +
            "https://outlook.office.com/mail.send</string>\r\n  <string>https://outlook.office." +
            "com/mailboxsettings.read</string>\r\n  <string>https://outlook.office.com/mailboxs" +
            "ettings.readwrite</string>\r\n  <string>https://outlook.office.com/people.read</st" +
            "ring>\r\n  <string>https://outlook.office.com/tasks.read</string>\r\n  <string>https" +
            "://outlook.office.com/tasks.readwrite</string>\r\n  <string>https://outlook.office" +
            ".com/user.read</string>\r\n  <string>https://outlook.office.com/user.readwrite</st" +
            "ring>\r\n  <string>https://outlook.office.com/user.readbasic.all</string>\r\n  <stri" +
            "ng>https://graph.microsoft.com/Analytics.Read</string>\r\n  <string>https://graph." +
            "microsoft.com/AppCatalog.Read.All</string>\r\n  <string>https://graph.microsoft.co" +
            "m/AppCatalog.ReadWrite.All</string>\r\n  <string>https://graph.microsoft.com/Booki" +
            "ngs.Read.All</string>\r\n  <string>https://graph.microsoft.com/BookingsAppointment" +
            ".ReadWrite.All</string>\r\n  <string>https://graph.microsoft.com/Bookings.ReadWrit" +
            "e.All</string>\r\n  <string>https://graph.microsoft.com/Bookings.Manage.All</strin" +
            "g>\r\n  <string>https://graph.microsoft.com/Calendars.Read</string>\r\n  <string>htt" +
            "ps://graph.microsoft.com/Calendars.Read.Shared</string>\r\n  <string>https://graph" +
            ".microsoft.com/Calendars.ReadWrite</string>\r\n  <string>https://graph.microsoft.c" +
            "om/Calendars.ReadWrite.Shared</string>\r\n  <string>https://graph.microsoft.com/Ch" +
            "annel.ReadBasic.All</string>\r\n  <string>https://graph.microsoft.com/Channel.Crea" +
            "te</string>\r\n  <string>https://graph.microsoft.com/Channel.Create.Group</string>" +
            "\r\n  <string>https://graph.microsoft.com/Channel.Delete.All</string>\r\n  <string>h" +
            "ttps://graph.microsoft.com/Channel.Delete.Group</string>\r\n  <string>https://grap" +
            "h.microsoft.com/ChannelSettings.Edit.Group</string>\r\n  <string>https://graph.mic" +
            "rosoft.com/ChannelSettings.Read.All</string>\r\n  <string>https://graph.microsoft." +
            "com/ChannelSettings.Read.Group</string>\r\n  <string>https://graph.microsoft.com/C" +
            "hannelSettings.ReadWrite.All</string>\r\n  <string>https://graph.microsoft.com/Cha" +
            "nnelMember.Read.All</string>\r\n  <string>https://graph.microsoft.com/ChannelMembe" +
            "r.ReadWrite.All</string>\r\n  <string>https://graph.microsoft.com/ChannelMessage.R" +
            "ead.All</string>\r\n  <string>https://graph.microsoft.com/ChannelMessage.Read.Grou" +
            "p</string>\r\n  <string>https://graph.microsoft.com/ChannelMessage.Send</string>\r\n" +
            "  <string>https://graph.microsoft.com/Chat.Read.All</string>\r\n  <string>https://" +
            "graph.microsoft.com/Chat.ReadBasic.All</string>\r\n  <string>https://graph.microso" +
            "ft.com/Chat.UpdatePolicyViolation.All</string>\r\n  <string>https://graph.microsof" +
            "t.com/Contacts.Read</string>\r\n  <string>https://graph.microsoft.com/Contacts.Rea" +
            "d.Shared</string>\r\n  <string>https://graph.microsoft.com/Contacts.ReadWrite</str" +
            "ing>\r\n  <string>https://graph.microsoft.com/Contacts.ReadWrite.Shared</string>\r\n" +
            "  <string>https://graph.microsoft.com/Device.Read</string>\r\n  <string>https://gr" +
            "aph.microsoft.com/Device.Command</string>\r\n  <string>https://graph.microsoft.com" +
            "/Directory.Read.All</string>\r\n  <string>https://graph.microsoft.com/Directory.Re" +
            "adWrite.All</string>\r\n  <string>https://graph.microsoft.com/Directory.AccessAsUs" +
            "er.All</string>\r\n  <string>https://graph.microsoft.com/Files.Read</string>\r\n  <s" +
            "tring>https://graph.microsoft.com/Files.Read.All</string>\r\n  <string>https://gra" +
            "ph.microsoft.com/Files.ReadWrite</string>\r\n  <string>https://graph.microsoft.com" +
            "/Files.ReadWrite.All</string>\r\n  <string>https://graph.microsoft.com/Group.Read." +
            "All</string>\r\n  <string>https://graph.microsoft.com/Group.ReadWrite.All</string>" +
            "\r\n  <string>https://graph.microsoft.com/GroupMember.Read.All</string>\r\n  <string" +
            ">https://graph.microsoft.com/GroupMember.ReadWrite.All</string>\r\n  <string>https" +
            "://graph.microsoft.com/IdentityProvider.Read.All</string>\r\n  <string>https://gra" +
            "ph.microsoft.com/IdentityProvider.ReadWrite.All</string>\r\n  <string>https://grap" +
            "h.microsoft.com/Mail.Read</string>\r\n  <string>https://graph.microsoft.com/Mail.R" +
            "eadBasic</string>\r\n  <string>https://graph.microsoft.com/Mail.ReadWrite</string>" +
            "\r\n  <string>https://graph.microsoft.com/Mail.Read.Shared</string>\r\n  <string>htt" +
            "ps://graph.microsoft.com/Mail.ReadWrite.Shared</string>\r\n  <string>https://graph" +
            ".microsoft.com/Mail.Send</string>\r\n  <string>https://graph.microsoft.com/Mail.Se" +
            "nd.Shared</string>\r\n  <string>https://graph.microsoft.com/MailboxSettings.Read</" +
            "string>\r\n  <string>https://graph.microsoft.com/MailboxSettings.ReadWrite</string" +
            ">\r\n  <string>https://graph.microsoft.com/Member.Read.Group</string>\r\n  <string>h" +
            "ttps://graph.microsoft.com/Member.Read.Hidden</string>\r\n  <string>https://graph." +
            "microsoft.com/Notes.Create</string>\r\n  <string>https://graph.microsoft.com/Notes" +
            ".Read</string>\r\n  <string>https://graph.microsoft.com/Notes.ReadWrite</string>\r\n" +
            "  <string>https://graph.microsoft.com/Notes.Read.All</string>\r\n  <string>https:/" +
            "/graph.microsoft.com/Notes.ReadWrite.All</string>\r\n  <string>https://graph.micro" +
            "soft.com/OnlineMeetings.Read</string>\r\n  <string>https://graph.microsoft.com/Onl" +
            "ineMeetings.ReadWrite</string>\r\n  <string>https://graph.microsoft.com/Organizati" +
            "on.Read.All</string>\r\n  <string>https://graph.microsoft.com/Organization.ReadWri" +
            "te.All</string>\r\n  <string>https://graph.microsoft.com/OrgContact.Read.All</stri" +
            "ng>\r\n  <string>https://graph.microsoft.com/Owner.Read.Group</string>\r\n  <string>" +
            "https://graph.microsoft.com/People.Read</string>\r\n  <string>https://graph.micros" +
            "oft.com/People.Read.All</string>\r\n  <string>https://graph.microsoft.com/Place.Re" +
            "ad.All</string>\r\n  <string>https://graph.microsoft.com/Place.ReadWrite.All</stri" +
            "ng>\r\n  <string>https://graph.microsoft.com/Presence.Read</string>\r\n  <string>htt" +
            "ps://graph.microsoft.com/Presence.Read.All</string>\r\n  <string>https://graph.mic" +
            "rosoft.com/PrivilegedAccess.ReadWrite.AzureAD</string>\r\n  <string>https://graph." +
            "microsoft.com/PrivilegedAccess.ReadWrite.AzureResources</string>\r\n  <string>http" +
            "s://graph.microsoft.com/Reports.Read.All</string>\r\n  <string>https://graph.micro" +
            "soft.com/SecurityEvents.Read.All</string>\r\n  <string>https://graph.microsoft.com" +
            "/SecurityEvents.ReadWrite.All</string>\r\n  <string>https://graph.microsoft.com/Se" +
            "curityActions.Read.All</string>\r\n  <string>https://graph.microsoft.com/SecurityA" +
            "ctions.ReadWrite.All</string>\r\n  <string>https://graph.microsoft.com/ServiceHeal" +
            "th.Read.All</string>\r\n  <string>https://graph.microsoft.com/ServiceMessage.Read." +
            "All</string>\r\n  <string>https://graph.microsoft.com/ServiceMessageViewpoint.Writ" +
            "e</string>\r\n  <string>https://graph.microsoft.com/Sites.Manage.All</string>\r\n  <" +
            "string>https://graph.microsoft.com/Sites.Read.All</string>\r\n  <string>https://gr" +
            "aph.microsoft.com/Sites.ReadWrite.All</string>\r\n  <string>https://graph.microsof" +
            "t.com/Sites.FullControl.All</string>\r\n  <string>https://graph.microsoft.com/Task" +
            "s.ReadWrite</string>\r\n  <string>https://graph.microsoft.com/Team.ReadBasic.All</" +
            "string>\r\n  <string>https://graph.microsoft.com/TeamMember.Read.All</string>\r\n  <" +
            "string>https://graph.microsoft.com/TeamMember.ReadWrite.All</string>\r\n  <string>" +
            "https://graph.microsoft.com/Teams.ReadBasic.All</string>\r\n  <string>https://grap" +
            "h.microsoft.com/TeamsApp.Read.Group</string>\r\n  <string>https://graph.microsoft." +
            "com/TeamsAppInstallation.ReadForUser</string>\r\n  <string>https://graph.microsoft" +
            ".com/TeamsAppInstallation.ReadWriteForUser</string>\r\n  <string>https://graph.mic" +
            "rosoft.com/TeamsAppInstallation.ReadForTeam</string>\r\n  <string>https://graph.mi" +
            "crosoft.com/TeamsAppInstallation.ReadWriteForTeam</string>\r\n  <string>https://gr" +
            "aph.microsoft.com/TeamSettings.Read.All</string>\r\n  <string>https://graph.micros" +
            "oft.com/TeamSettings.Read.Group</string>\r\n  <string>https://graph.microsoft.com/" +
            "TeamSettings.ReadWrite.All</string>\r\n  <string>https://graph.microsoft.com/Teams" +
            "Settings.Read.All</string>\r\n  <string>https://graph.microsoft.com/TeamsSettings." +
            "ReadWrite.All</string>\r\n  <string>https://graph.microsoft.com/TeamsTab.Create</s" +
            "tring>\r\n  <string>https://graph.microsoft.com/TeamsTab.Create.Group</string>\r\n  " +
            "<string>https://graph.microsoft.com/TeamsTab.Delete.Group</string>\r\n  <string>ht" +
            "tps://graph.microsoft.com/TeamsTab.Edit.Group</string>\r\n  <string>https://graph." +
            "microsoft.com/TeamsTab.Read.All</string>\r\n  <string>https://graph.microsoft.com/" +
            "TeamsTab.Read.Group</string>\r\n  <string>https://graph.microsoft.com/TeamsTab.Rea" +
            "dWrite.All</string>\r\n  <string>https://graph.microsoft.com/ThreatIndicators.Read" +
            "Write.OwnedBy</string>\r\n  <string>https://graph.microsoft.com/ThreatIndicators.R" +
            "ead.All</string>\r\n  <string>https://graph.microsoft.com/User.Export.All</string>" +
            "\r\n  <string>https://graph.microsoft.com/User.Invite.All</string>\r\n  <string>http" +
            "s://graph.microsoft.com/User.ManageIdentities.All</string>\r\n  <string>https://gr" +
            "aph.microsoft.com/User.Read</string>\r\n  <string>https://graph.microsoft.com/User" +
            ".Read.All</string>\r\n  <string>https://graph.microsoft.com/User.ReadBasic.All</st" +
            "ring>\r\n  <string>https://graph.microsoft.com/User.ReadWrite</string>\r\n  <string>" +
            "https://graph.microsoft.com/User.ReadWrite.All</string>\r\n  <string>https://graph" +
            ".microsoft.com/UserActivity.ReadWrite.CreatedByApp</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection PredefinedScopes {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["PredefinedScopes"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>offline_access</string>\r\n  <string>https://graph.microsoft.com/Calendars.R" +
            "ead</string>\r\n  <string>https://graph.microsoft.com/Calendars.Read.Shared</strin" +
            "g>\r\n  <string>https://graph.microsoft.com/Calendars.ReadWrite</string>\r\n  <strin" +
            "g>https://graph.microsoft.com/Calendars.ReadWrite.Shared</string>\r\n  <string>htt" +
            "ps://graph.microsoft.com/Contacts.Read</string>\r\n  <string>https://graph.microso" +
            "ft.com/Contacts.Read.Shared</string>\r\n  <string>https://graph.microsoft.com/Cont" +
            "acts.ReadWrite</string>\r\n  <string>https://graph.microsoft.com/Contacts.ReadWrit" +
            "e.Shared</string>\r\n  <string>https://graph.microsoft.com/Mail.Read</string>\r\n  <" +
            "string>https://graph.microsoft.com/Mail.ReadWrite</string>\r\n  <string>https://gr" +
            "aph.microsoft.com/Mail.Read.Shared</string>\r\n  <string>https://graph.microsoft.c" +
            "om/Mail.ReadWrite.Shared</string>\r\n  <string>https://graph.microsoft.com/Mail.Se" +
            "nd</string>\r\n  <string>https://graph.microsoft.com/Mail.Send.Shared</string>\r\n  " +
            "<string>https://graph.microsoft.com/MailboxSettings.Read</string>\r\n  <string>htt" +
            "ps://graph.microsoft.com/MailboxSettings.ReadWrite</string>\r\n  <string>https://g" +
            "raph.microsoft.com/People.Read</string>\r\n  <string>https://graph.microsoft.com/T" +
            "asks.ReadWrite</string>\r\n  <string>https://graph.microsoft.com/User.Read</string" +
            ">\r\n  <string>https://graph.microsoft.com/User.ReadWrite</string>\r\n  <string>http" +
            "s://graph.microsoft.com/User.ReadBasic.All</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection DefaultScopes {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["DefaultScopes"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection CustomDefinedScopes {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["CustomDefinedScopes"]));
            }
            set {
                this["CustomDefinedScopes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastV2WebAppClientID {
            get {
                return ((string)(this["LastV2WebAppClientID"]));
            }
            set {
                this["LastV2WebAppClientID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastV2WebAppRedirectUri {
            get {
                return ((string)(this["LastV2WebAppRedirectUri"]));
            }
            set {
                this["LastV2WebAppRedirectUri"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastV2WebAppScopes {
            get {
                return ((string)(this["LastV2WebAppScopes"]));
            }
            set {
                this["LastV2WebAppScopes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastV2WebAppClientSecret {
            get {
                return ((string)(this["LastV2WebAppClientSecret"]));
            }
            set {
                this["LastV2WebAppClientSecret"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastV2MobileAppClientID {
            get {
                return ((string)(this["LastV2MobileAppClientID"]));
            }
            set {
                this["LastV2MobileAppClientID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastV2MobileAppScopes {
            get {
                return ((string)(this["LastV2MobileAppScopes"]));
            }
            set {
                this["LastV2MobileAppScopes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool NeedUpgrade {
            get {
                return ((bool)(this["NeedUpgrade"]));
            }
            set {
                this["NeedUpgrade"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastMailboxViewerClientID {
            get {
                return ((string)(this["LastMailboxViewerClientID"]));
            }
            set {
                this["LastMailboxViewerClientID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastWebAppAppOnlyTenantName {
            get {
                return ((string)(this["LastWebAppAppOnlyTenantName"]));
            }
            set {
                this["LastWebAppAppOnlyTenantName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastWebAppAppOnlyClientID {
            get {
                return ((string)(this["LastWebAppAppOnlyClientID"]));
            }
            set {
                this["LastWebAppAppOnlyClientID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastWebAppAppOnlyCertPath {
            get {
                return ((string)(this["LastWebAppAppOnlyCertPath"]));
            }
            set {
                this["LastWebAppAppOnlyCertPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastWebAppAppOnlyCertPass {
            get {
                return ((string)(this["LastWebAppAppOnlyCertPass"]));
            }
            set {
                this["LastWebAppAppOnlyCertPass"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LogFolderPath {
            get {
                return ((string)(this["LogFolderPath"]));
            }
            set {
                this["LogFolderPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Static")]
        public string LogFileStyle {
            get {
                return ((string)(this["LogFileStyle"]));
            }
            set {
                this["LogFileStyle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AllowAutoRedirect {
            get {
                return ((bool)(this["AllowAutoRedirect"]));
            }
            set {
                this["AllowAutoRedirect"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastWebAppAppOnlyByKeyTenantName {
            get {
                return ((string)(this["LastWebAppAppOnlyByKeyTenantName"]));
            }
            set {
                this["LastWebAppAppOnlyByKeyTenantName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastWebAppAppOnlyByKeyClientID {
            get {
                return ((string)(this["LastWebAppAppOnlyByKeyClientID"]));
            }
            set {
                this["LastWebAppAppOnlyByKeyClientID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastWebAppAppOnlyByKeyClientSecret {
            get {
                return ((string)(this["LastWebAppAppOnlyByKeyClientSecret"]));
            }
            set {
                this["LastWebAppAppOnlyByKeyClientSecret"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastBuiltInAppScopes {
            get {
                return ((string)(this["LastBuiltInAppScopes"]));
            }
            set {
                this["LastBuiltInAppScopes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("389b1b32-b5d5-43b2-bddc-84ce938d6737")]
        public string BuiltInAppClientId {
            get {
                return ((string)(this["BuiltInAppClientId"]));
            }
            set {
                this["BuiltInAppClientId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("urn:ietf:wg:oauth:2.0:oob")]
        public string BuiltInAppRedirectUri {
            get {
                return ((string)(this["BuiltInAppRedirectUri"]));
            }
            set {
                this["BuiltInAppRedirectUri"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Office365APIEditor")]
        public string CustomUserAgent {
            get {
                return ((string)(this["CustomUserAgent"]));
            }
            set {
                this["CustomUserAgent"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int CustomUserAgentMode {
            get {
                return ((int)(this["CustomUserAgentMode"]));
            }
            set {
                this["CustomUserAgentMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastV2WebAppAppOnlyByPasswordForMicrosoftGraphTenantName {
            get {
                return ((string)(this["LastV2WebAppAppOnlyByPasswordForMicrosoftGraphTenantName"]));
            }
            set {
                this["LastV2WebAppAppOnlyByPasswordForMicrosoftGraphTenantName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastV2WebAppAppOnlyByPasswordForMicrosoftGraphClientID {
            get {
                return ((string)(this["LastV2WebAppAppOnlyByPasswordForMicrosoftGraphClientID"]));
            }
            set {
                this["LastV2WebAppAppOnlyByPasswordForMicrosoftGraphClientID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastV2WebAppAppOnlyByPasswordForMicrosoftGraphClientSecret {
            get {
                return ((string)(this["LastV2WebAppAppOnlyByPasswordForMicrosoftGraphClientSecret"]));
            }
            set {
                this["LastV2WebAppAppOnlyByPasswordForMicrosoftGraphClientSecret"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string NewerInstallerPath {
            get {
                return ((string)(this["NewerInstallerPath"]));
            }
            set {
                this["NewerInstallerPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SystemLogging {
            get {
                return ((bool)(this["SystemLogging"]));
            }
            set {
                this["SystemLogging"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0, 0, 0")]
        public global::System.Drawing.Rectangle MailboxViewerFormBounds {
            get {
                return ((global::System.Drawing.Rectangle)(this["MailboxViewerFormBounds"]));
            }
            set {
                this["MailboxViewerFormBounds"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Normal")]
        public global::System.Windows.Forms.FormWindowState MailboxViewerFormWindowState {
            get {
                return ((global::System.Windows.Forms.FormWindowState)(this["MailboxViewerFormWindowState"]));
            }
            set {
                this["MailboxViewerFormWindowState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0, 0, 0")]
        public global::System.Drawing.Rectangle RequestFormBounds {
            get {
                return ((global::System.Drawing.Rectangle)(this["RequestFormBounds"]));
            }
            set {
                this["RequestFormBounds"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Normal")]
        public global::System.Windows.Forms.FormWindowState RequestFormWindowState {
            get {
                return ((global::System.Windows.Forms.FormWindowState)(this["RequestFormWindowState"]));
            }
            set {
                this["RequestFormWindowState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastV2WebAppTenantName {
            get {
                return ((string)(this["LastV2WebAppTenantName"]));
            }
            set {
                this["LastV2WebAppTenantName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastV2MobileAppTenantName {
            get {
                return ((string)(this["LastV2MobileAppTenantName"]));
            }
            set {
                this["LastV2MobileAppTenantName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastV2MobileAppRedirectUri {
            get {
                return ((string)(this["LastV2MobileAppRedirectUri"]));
            }
            set {
                this["LastV2MobileAppRedirectUri"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ReplacePlusSignInTheRequestURL {
            get {
                return ((bool)(this["ReplacePlusSignInTheRequestURL"]));
            }
            set {
                this["ReplacePlusSignInTheRequestURL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastSpoAppOnlyByKeyTenantName {
            get {
                return ((string)(this["LastSpoAppOnlyByKeyTenantName"]));
            }
            set {
                this["LastSpoAppOnlyByKeyTenantName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastSpoAppOnlyByKeyClientID {
            get {
                return ((string)(this["LastSpoAppOnlyByKeyClientID"]));
            }
            set {
                this["LastSpoAppOnlyByKeyClientID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastSpoAppOnlyByKeyClientSecret {
            get {
                return ((string)(this["LastSpoAppOnlyByKeyClientSecret"]));
            }
            set {
                this["LastSpoAppOnlyByKeyClientSecret"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ReplaceSharpSignInTheRequestURL {
            get {
                return ((bool)(this["ReplaceSharpSignInTheRequestURL"]));
            }
            set {
                this["ReplaceSharpSignInTheRequestURL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastV2WebAppAppOnlyByCertTenantName {
            get {
                return ((string)(this["LastV2WebAppAppOnlyByCertTenantName"]));
            }
            set {
                this["LastV2WebAppAppOnlyByCertTenantName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastV2WebAppAppOnlyByCertClientID {
            get {
                return ((string)(this["LastV2WebAppAppOnlyByCertClientID"]));
            }
            set {
                this["LastV2WebAppAppOnlyByCertClientID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastV2WebAppAppOnlyByCertCertPath {
            get {
                return ((string)(this["LastV2WebAppAppOnlyByCertCertPath"]));
            }
            set {
                this["LastV2WebAppAppOnlyByCertCertPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastV2WebAppAppOnlyByCertCertPass {
            get {
                return ((string)(this["LastV2WebAppAppOnlyByCertCertPass"]));
            }
            set {
                this["LastV2WebAppAppOnlyByCertCertPass"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Office365APIEditor.Settings.AccessTokenWizardAppContainer AccessTokenWizardApps {
            get {
                return ((global::Office365APIEditor.Settings.AccessTokenWizardAppContainer)(this["AccessTokenWizardApps"]));
            }
            set {
                this["AccessTokenWizardApps"] = value;
            }
        }
    }
}
